version: "3"
services:
  cadot.info-E:
    image: cadotinfo/symfony5
    container_name: cadot.info-testTools
    volumes:
      - .:/app
    networks:
      - web
    restart: always
    ports:
      - 80

networks:
  web:
    external: true
